name: reliance_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.5
  dio: ^3.0.10
  adaptive_dialog: ^0.9.0+1
  provider_architecture: ^1.1.1+1
  get_it: ^5.0.1
  flushbar: ^1.10.4
  cached_network_image: ^2.4.1
  flutter_svg:
  google_fonts: ^1.1.1
  animated_bottom_navigation_bar: ^0.2.1
  eva_icons_flutter:
  smooth_star_rating:
  carousel_slider: ^2.3.1
  image_picker: ^0.6.7+21

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/